### ISSUE TITLE
Error running the example code

### ISSUE THREAD

**Issue by osavigne** [ItzRabbs/puppeteer-pro#362]
with   "puppeteer-pro": "^1.5.0"

Not Working :
Testing the 🐱‍👤 avoidDetection 🐱‍👤 plugin..
Testing the recaptcha solver..
(node:7444) UnhandledPromiseRejectionWarning: Error: Evaluation failed: DOMException: Failed to execute 'createBuffer' on 'BaseAudioContext': createBuffer(1, 4294926435, 16000) failed.
    at sliceAudio (__puppeteer_evaluation_script__:26:28)
    at __puppeteer_evaluation_script__:136:22
    at ExecutionContext._evaluateInternal (D:\Trabajo\Personal\Preuser\puppeteer-pro-recaptcha-solver\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\Trabajo\Personal\Preuser\puppeteer-pro-recaptcha-solver\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async SolveRecaptchaPlugin.solveRecaptcha (D:\Trabajo\Personal\Preuser\puppeteer-pro-recaptcha-solver\node_modules\puppeteer-pro\plugins\solve.recaptcha\index.js:56:32)
    at async D:\Trabajo\Personal\Preuser\puppeteer-pro-recaptcha-solver\examples\demo.js:22:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by osavigne** [comment]
I realize that in my case "document.querySelector('iframe[src*="api2/anchor"]').contentDocument" is null, so i would be nice if you guys can implement the captcha solver with puppeteer click() function on .frames(), instead of page.evaluate() functions, thanks for the great work

**Comment by ItzRabbs** [comment]
To start with, the [wit.ai api is having issues](https://github.com/wit-ai/wit/issues/2234) so I can't quite test anything. 

That said, it does seem like your issue is fetching the audio clip, not that anything in the html is missing. The error stack has **\puppeteer-pro\plugins\solve.recaptcha\index.js:56:32** which correlates to [line 64 in this file](https://github.com/ItzRabbs/puppeteer-pro/blob/master/src/plugins/solve.recaptcha/index.ts#L64).

That line comes after the audioUrl has already been extracted from the recaptcha iframe. Can you check and see if you can play the audio manually in the recaptcha?
